add json rules engine simplified as dependency
relayplatform/rjsf-conditionals pull request #1
Opened 2022-06-14 16:30 UTC by AdelRashed97

Improve performance and reduce time delay by only running rules if the form data changed and one of fields that are conditioned one has changed.

2022-06-16 16:19 UTC, mvlhotra approved these changes
Looks good to me. Two things:
- Check your variable spelling
- Were those tests failing already? Are we okay to skip them?

2022-06-16 16:19 UTC, mvlhotra commented on src/rulesRunner.js
> +  const condtionedFields = listAllFields(rules);
check spelling

2022-06-16 16:19 UTC, mvlhotra commented on test/applyRules.render.test.js
>    const runRules = rulesRunner(schema, {}, RULES, Engine);
Were the above tests failing already?

2022-06-16 16:21 UTC, Haegin requested changes
The code looks good but I think we need to get the tests working - they're all tests around when we re-render and which version of the schema is used.

2022-06-16 16:21 UTC, Haegin commented on src/applyRules.js
> +  Engine = SimplifiedEngine,
If we take this default out,  can we support both the engines and remove the need to import it? If so that's going to make it a lot more likely that we can get this accepted and merged upstream.

2022-06-16 16:21 UTC, Haegin commented on .github/workflows/gh_pages.yml
> -name: Publish playground
Should we keep this so we still get github pages for docs?

2022-06-16 16:21 UTC, Haegin commented on test/applyRules.render.test.js
> +test.skip("NO re render on same data", async () => {
Shouldn't this test still pass? Seems like it's very related to what we're changing here?

2022-06-16 16:21 UTC, Haegin commented on test/applyRules.render.test.js
> +test.skip("Re render on formData change", async () => {
This also seems like an important test to get working.

2022-06-16 16:21 UTC, Haegin commented on test/applyRules.test.js
> +test.skip("Re render on rule change", async () => {
:repeat:

2022-06-16 16:23 UTC, adelhrashed commented on .github/workflows/gh_pages.yml
> -name: Publish playground
up to you

2022-06-16 16:25 UTC, adelhrashed commented on src/applyRules.js
> +  Engine = SimplifiedEngine,
we can remove this but still it will not support both engines because the listAllFields method in the utils imports a method from the json simplified engine

2022-06-17 14:46 UTC, Haegin commented on .github/workflows/gh_pages.yml
> -name: Publish playground
Yeah, let's bring this back then I think this PR is good to go.

2022-06-17 16:54 UTC, Haegin approved these changes

2022-06-17 18:13 UTC, merged